import {readFile} from 'node:fs/promises';
import {PlanSchema,type Action,type Condition} from '../src/actions/schema.js';
import type {Agent} from '../src/agent/Agent.js';
export interface ComplexScenario {id:string;view:string;actions:Action[];criteria:Condition[];oracle:(agent:Agent)=>Promise<boolean>}
const click=(name:string):Action=>({type:'click',target:{role:'button',name}});
const fill=(label:string,value:string):Action=>({type:'fill',target:{label},value});
const select=(label:string,value:string):Action=>({type:'select',target:{label},value});
const check=(label:string):Action=>({type:'check',target:{label}});
const table=(name:string,key:string):Action=>({type:'extract',target:{role:'table',name},format:'table',key});
const download=(name:string):Action=>({type:'download',target:{role:'button',name}});
const extracted=(agent:Agent)=>JSON.stringify(agent.browser.extractions.map(e=>e.value));
async function fileContains(agent:Agent,filename:string,values:string[]){const file=agent.browser.downloads.find(d=>d.filename===filename);if(!file)return false;const text=await readFile(file.path,'utf8');return values.every(value=>text.includes(value));}
export const complexScenarios:ComplexScenario[]=[
 {id:'compare',view:'products',actions:[fill('Search products','keyboard'),select('Category','Keyboard'),select('Connection','Wireless'),fill('Maximum price EUR','100'),check('In stock only'),select('Sort products','Price: low to high'),click('View Trail K2 details'),{type:'extract',target:{id:'product-detail-content'},format:'text',key:'details'},click('Back to products'),check('Compare Trail K2'),check('Compare Summit Air'),click('Compare selected products'),table('Product comparison','comparison'),download('Download comparison CSV')],criteria:[{type:'download_created',value:'northstar-comparison.csv'},{type:'extraction_contains',value:'Summit Air'}],oracle:async agent=>{
   const rows=await agent.browser.page.getByRole('table',{name:'Product comparison'}).locator('tbody tr').allTextContents();
   const state=await agent.browser.page.evaluate(()=>JSON.parse(sessionStorage.getItem('northstar-v2-product-flow')??'{}'));
   return rows.length===2&&rows[0]!.includes('Trail K2')&&rows[0]!.includes('480 g')&&rows[1]!.includes('120 hours')&&extracted(agent).includes('EUR 69')&&await fileContains(agent,'northstar-comparison.csv',['Trail K2','Summit Air','EUR 89','610 g'])&&state.filters['product-connection']==='Wireless'&&state.filters['product-stock']===true&&agent.browser.page.url().includes('product-comparison.html')&&agent.browser.responses.some(r=>r.resource==='document'&&r.url.includes('product-details.html'));}},
 {id:'travel',view:'travel',actions:[select('From','Paris'),select('To','Lyon'),fill('Departure date','2026-10-15'),select('Passengers','2 adults'),{type:'click',target:{text:'Accessibility & route preferences'}},check('Step-free routes only'),check('Refundable fares only'),select('Maximum interchanges','1'),fill('Maximum total price EUR','120'),click('Find journeys'),select('Sort journeys','Total price: low to high'),click('View Flex Regional details'),{type:'extract',target:{role:'dialog',name:'Journey details'},format:'text',key:'route'},click('Close Journey details'),click('Shortlist Flex Regional'),{type:'extract',target:{id:'itinerary-summary'},format:'text',key:'itinerary'},download('Download itinerary')],criteria:[{type:'download_created',value:'northstar-itinerary.txt'},{type:'text_exists',value:'Itinerary saved locally. No booking was made.'}],oracle:async agent=>{
   const saved=await agent.browser.page.evaluate(()=>JSON.parse(localStorage.getItem('northstar-v2-itinerary')??'{}'));
   return saved.from==='Paris'&&saved.to==='Lyon'&&saved.date==='2026-10-15'&&saved.passengers==='2 adults'&&saved.stepfree&&saved.refund&&saved.service==='Flex Regional'&&saved.totalEUR===90&&saved.durationMinutes===175&&extracted(agent).includes('Regional 4')&&await fileContains(agent,'northstar-itinerary.txt',['Flex Regional','2026-10-15','90','NOT A BOOKING'])&&agent.browser.page.url().includes('itinerary.html')&&agent.browser.responses.some(r=>r.resource==='document'&&r.url.includes('journey-results.html'));}},
 {id:'billing',view:'billing',actions:[fill('Search invoices','Atlas Studio'),select('Invoice status','Overdue'),select('Invoice period','September 2026'),select('Account owner','Maya Chen'),table('Invoices','invoices'),click('View INV-2609-04'),table('Invoice line items','lineItems'),download('Download this invoice')],criteria:[{type:'download_created',value:'INV-2609-04.txt'},{type:'extraction_contains',value:'Workspace Pro'}],oracle:async agent=>{
   const invoices=agent.browser.extractions.map(e=>e.value).find(value=>Array.isArray(value)&&JSON.stringify(value).includes('INV-2609-04')&&JSON.stringify(value).includes('Atlas Studio'));
   const filters=await agent.browser.page.evaluate(()=>JSON.parse(sessionStorage.getItem('northstar-v2-billing-flow')??'{}'));
   return Array.isArray(invoices)&&invoices.length===2&&filters['invoice-period']==='2026-09'&&agent.browser.page.url().includes('invoice-details.html?id=INV-2609-04')&&extracted(agent).includes('240')&&await fileContains(agent,'INV-2609-04.txt',['Atlas Studio','Workspace Pro: EUR 180','Research add-on: EUR 60','Total: EUR 240']);}},
 {id:'analytics',view:'analytics',actions:[select('Quarter','Q3 2026'),select('Sales channel','Direct'),table('Monthly revenue','revenue'),click('View September breakdown'),table('Channel breakdown','september'),click('Close Monthly breakdown'),download('Download report CSV')],criteria:[{type:'download_created',value:'northstar-revenue-report.csv'},{type:'extraction_contains',value:'3900'}],oracle:async agent=>(await agent.browser.page.locator('#analytics-total').innerText()).replace(/[^0-9]/g,'')==='9400'&&await agent.browser.page.locator('#analytics-orders').innerText()==='94'&&extracted(agent).includes('2400')&&extracted(agent).includes('3100')&&await fileContains(agent,'northstar-revenue-report.csv',['July,2400,24','August,3100,31','September,3900,39'])},
 {id:'settings',view:'settings',actions:[select('Display currency','GBP'),select('Workspace timezone','Europe/London'),check('Enable weekly digest preview'),select('Digest day','Friday'),fill('Digest time','08:30'),check('Enable quiet hours'),fill('Quiet hours start','21:00'),fill('Quiet hours end','07:00'),click('Review preference changes'),table('Preference changes','changes'),click('Save preferences locally'),{type:'reload'}],criteria:[{type:'input_value_equals',target:{label:'Display currency'},value:'GBP'},{type:'input_value_equals',target:{label:'Digest time'},value:'08:30'},{type:'checkbox_checked',target:{label:'Enable quiet hours'}}],oracle:async agent=>{
   const saved=await agent.browser.page.evaluate(()=>JSON.parse(localStorage.getItem('northstar-v2-settings')??'{}'));
   return saved.currency==='GBP'&&saved.timezone==='Europe/London'&&saved.digest===true&&saved.day==='Friday'&&saved.time==='08:30'&&saved.quiet===true&&saved.quietStart==='21:00'&&saved.quietEnd==='07:00'&&await agent.browser.page.getByLabel('Quiet hours end').inputValue()==='07:00'&&await agent.browser.page.getByLabel('Digest day').inputValue()==='Friday';}},
 {id:'documents',view:'documents',actions:[fill('Search documents','revenue'),select('Folder','Finance'),select('Document format','CSV'),select('Sort documents','Newest first'),click('Preview Q3 revenue summary'),{type:'extract',target:{role:'dialog',name:'Document preview'},format:'text',key:'document'},download('Download this document')],criteria:[{type:'download_created',value:'q3-revenue-summary.csv'},{type:'extraction_contains',value:'2026-09-16'}],oracle:async agent=>extracted(agent).includes('Maya Chen')&&await agent.browser.page.locator('#document-rows tr').count()===2&&await fileContains(agent,'q3-revenue-summary.csv',['July,4200,42','August,5300,53','September,6800,68'])},
 {id:'close',view:'close',actions:[select('Quarter','Q3 2026'),select('Sales channel','Direct'),click('Open revenue report'),table('Close revenue','revenue'),click('Inspect booked ledger'),table('Booked ledger','ledger'),click('View ADJ-042 adjustment'),table('Adjustment record','adjustment'),click('Read close policy'),{type:'extract',target:{css:'.case-policy'},format:'text',key:'policy'},click('Prepare close review'),fill('Revenue EUR','9400'),fill('Booked ledger EUR','9300'),fill('Variance EUR','100'),select('Open adjustment','ADJ-042'),select('Review decision','Needs review'),click('Save review draft'),download('Download close dossier')],criteria:[{type:'download_created',value:'northstar-close-review.txt'},{type:'text_exists',value:'Ready for a human reviewer'}],oracle:async agent=>{
   const selected=await agent.browser.page.evaluate(()=>JSON.parse(sessionStorage.getItem('northstar-v3-close-scope')??'{}'));
   const saved=await agent.browser.page.evaluate(()=>JSON.parse(localStorage.getItem('northstar-v3-close-report')??'{}'));
   const documents=new Set(agent.browser.responses.filter(r=>r.resource==='document').map(r=>new URL(r.url).pathname));
   return selected.quarter==='Q3 2026'&&selected.channel==='Direct'&&saved.valid===true&&saved.revenue===9400&&saved.booked===9300&&saved.variance===100&&saved.adjustment==='ADJ-042'&&saved.decision==='Needs review'&&['/lab/workspace.html','/lab/close-revenue.html','/lab/close-ledger.html','/lab/close-adjustment.html','/lab/close-policy.html','/lab/close-review.html'].every(path=>documents.has(path))&&['2400','3100','3900','9400','3800','9300','Pending — not booked','Any non-zero variance'].every(value=>extracted(agent).includes(value))&&await fileContains(agent,'northstar-close-review.txt',['Revenue: EUR 9400','Booked ledger: EUR 9300','Variance: EUR 100','ADJ-042 · pending, not booked','Decision: Needs review','No ledger entry was posted']);}},
 {id:'incident',view:'incident',actions:[select('Service','API Gateway'),select('Severity','High'),select('Time window','Last 24 hours'),table('Incident alerts','alerts'),click('Open INC-204'),table('Incident timeline','timeline'),click('Inspect request metrics'),table('Request metrics','metrics'),click('Compare deployments'),table('Deployment comparison','deployments'),click('Read incident runbook'),{type:'extract',target:{css:'.case-policy'},format:'text',key:'runbook'},click('Prepare incident brief'),select('Incident ID','INC-204'),select('Affected endpoint','/v1/search'),fill('Baseline 429 rate percent','0.4'),fill('Incident 429 rate percent','12.4'),select('Triggering deployment','dep-7c3'),select('Configuration change','burst_limit: 100 → 20'),select('Decision','Needs engineer review'),click('Save incident brief locally'),download('Download incident brief')],criteria:[{type:'download_created',value:'northstar-incident-brief.txt'},{type:'text_exists',value:'Ready for engineer review'}],oracle:async agent=>{
   const filters=await agent.browser.page.evaluate(()=>JSON.parse(sessionStorage.getItem('northstar-v3-incident-filters')??'{}'));
   const saved=await agent.browser.page.evaluate(()=>JSON.parse(localStorage.getItem('northstar-v3-incident-brief')??'{}'));
   const documents=new Set(agent.browser.responses.filter(r=>r.resource==='document').map(r=>new URL(r.url).pathname));
   return filters.service==='API Gateway'&&filters.severity==='High'&&filters.window==='Last 24 hours'&&saved.valid===true&&saved.incident==='INC-204'&&saved.endpoint==='/v1/search'&&saved.baseline===0.4&&saved.rate===12.4&&saved.deployment==='dep-7c3'&&saved.change==='burst_limit: 100 → 20'&&saved.decision==='Needs engineer review'&&['/lab/workspace.html','/lab/incident-detail.html','/lab/incident-metrics.html','/lab/incident-deployments.html','/lab/incident-runbook.html','/lab/incident-brief.html'].every(path=>documents.has(path))&&['INC-204','429 rate crossed 10%','0.4%','12.4%','dep-7c3','100 → 20','Do not mark resolved'].every(value=>extracted(agent).includes(value))&&await fileContains(agent,'northstar-incident-brief.txt',['Incident: INC-204','Endpoint: /v1/search','429 baseline: 0.4%','429 during incident: 12.4%','Triggering deployment: dep-7c3','Needs engineer review','No rollback']);}},
];
export const planFor=(scenario:ComplexScenario,goal:string)=>PlanSchema.parse({goal,steps:['Apply the requested scope','Inspect details and extract evidence','Verify the saved result'],actions:scenario.actions,completion:scenario.criteria});
